# Generated by Django 4.2.9 on 2024-06-26 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0003_userwallet_usertransaction_userportfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlayStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('bought_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPlayWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_name', models.CharField(max_length=50)),
                ('balance', models.DecimalField(decimal_places=2, default=100000, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'wallet_name')},
            },
        ),
        migrations.CreateModel(
            name='UserStockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('bought_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sold_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_spending', models.DecimalField(decimal_places=2, max_digits=15)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_sale_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('change_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.userplaywallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserWalletHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.userplaywallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='usertransaction',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usertransaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userwallet',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserPortfolio',
        ),
        migrations.DeleteModel(
            name='UserTransaction',
        ),
        migrations.DeleteModel(
            name='UserWallet',
        ),
        migrations.AddField(
            model_name='userplaystock',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.userplaywallet'),
        ),
        migrations.AlterUniqueTogether(
            name='userplaystock',
            unique_together={('wallet', 'symbol')},
        ),
    ]
