# Generated by Django 4.2.9 on 2024-07-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_userstockhistory_bought_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwallethistory',
            name='stocks_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userwallethistory',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
