# Generated by Django 4.2.9 on 2024-06-08 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sudoku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzle', models.TextField()),
                ('current_state', models.TextField()),
                ('solution', models.TextField(blank=True, null=True)),
                ('difficulty', models.CharField(max_length=10)),
                ('time', models.IntegerField(default=0)),
                ('is_finished', models.BooleanField(default=False)),
                ('win', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_sudoku_games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
